### ISSUE TITLE
implement really good logging

### ISSUE THREAD

**Issue by skyhighwings** [skyhighwings/flixy#17]
probably by using some library out of https://github.com/avelino/awesome-go#logging

**Comment by skyhighwings** [comment]
Actually, the Negroni logger I picked really annoys me. I'm going to have to write my own at some point, then, I guess.

**Comment by skyhighwings** [comment]
Okay, I was dumb and didn't see `NewCustomMiddleware`, which is what I *should* have been using. Sorry, @meatballhat, your thing is actually pretty neat.

**Comment by meatballhat** [comment]
@skyhighwings :smiley_cat: :metal: sounds like I could make it more obvious, though...

**Comment by skyhighwings** [comment]
@meatballhat I'll be happy to contribute to the README to make it more obvious! Give me a few minutes and I'll send in a few suggestions.

**Comment by skyhighwings** [comment]
I sent in a couple of pull requests. I hope they're up to your standards!
