### ISSUE TITLE
determine if `Session` really needs to export `members` as json right now

### ISSUE THREAD

**Issue by skyhighwings** [skyhighwings/flixy#2]
it seems kind of useless to know what other IDs are in it. I can't actually think of a good use for it unless users can set a nickname for themselves. Which, come to think of it, sounds like a neat idea.

**Comment by Xe** [comment]
Leave it being displayed for now. Easier to just say it's unsupported.

**Comment by skyhighwings** [comment]
That's pretty much what I was thinking, yeah.

**Comment by skyhighwings** [comment]
It would be pretty trivial to add `nick` to the list of arguments in `flixy join` and `flixy new`, as a reference to the above musings on nicknames.

**Comment by skyhighwings** [comment]
actually I just realized `flixy new` would have to take a `map[string]interface{}` instead of `map[string]int` as it does currently, as mixing map value types in golang is verboten, as far as I can tell

**Comment by skyhighwings** [comment]
Closing as this is no longer in consideration, since we're adding nicks now.
